services:
  sustainhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sustainhub-webapp
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - VIRTUAL_PORT=3001
      - VIRTUAL_HOST=sustainhub.dev.tk.sg
    volumes:
      # Mount database directory for persistence
      - ./data:/app/data
    restart: unless-stopped
    networks:
      devtksg: # same network that our reverse proxy is on

networks:
  devtksg:
    external: true
